/*
 * data.js — Curated content for the Baby Keyboard Game.
 *
 * Two pools of items. Each item is { char, en, bn } where:
 *   - char : the emoji glyph shown on screen (also upgraded to a crisp SVG by Twemoji)
 *   - en   : the English word spoken aloud (Web Speech API)
 *   - bn   : the Bangla (Bengali) word spoken aloud when the language is set to বাংলা
 *
 * Exposed on the global object so plain <script> tags (no bundler / no modules)
 * keep working when opened directly from disk or served by GitHub Pages.
 */
(function (global) {
  'use strict';

  // Friendly, recognisable animals for a two-year-old.
  var ANIMALS = [
    { char: '🐶', en: 'Dog', bn: 'কুকুর' },
    { char: '🐱', en: 'Cat', bn: 'বিড়াল' },
    { char: '🐭', en: 'Mouse', bn: 'ইঁদুর' },
    { char: '🐹', en: 'Hamster', bn: 'হ্যামস্টার' },
    { char: '🐰', en: 'Bunny', bn: 'খরগোশ' },
    { char: '🦊', en: 'Fox', bn: 'শিয়াল' },
    { char: '🐻', en: 'Bear', bn: 'ভালুক' },
    { char: '🐼', en: 'Panda', bn: 'পান্ডা' },
    { char: '🐨', en: 'Koala', bn: 'কোয়ালা' },
    { char: '🐯', en: 'Tiger', bn: 'বাঘ' },
    { char: '🦁', en: 'Lion', bn: 'সিংহ' },
    { char: '🐮', en: 'Cow', bn: 'গরু' },
    { char: '🐷', en: 'Pig', bn: 'শূকর' },
    { char: '🐸', en: 'Frog', bn: 'ব্যাঙ' },
    { char: '🐵', en: 'Monkey', bn: 'বানর' },
    { char: '🐔', en: 'Chicken', bn: 'মুরগি' },
    { char: '🐧', en: 'Penguin', bn: 'পেঙ্গুইন' },
    { char: '🐦', en: 'Bird', bn: 'পাখি' },
    { char: '🐤', en: 'Baby Chick', bn: 'ছানা' },
    { char: '🦆', en: 'Duck', bn: 'হাঁস' },
    { char: '🦉', en: 'Owl', bn: 'পেঁচা' },
    { char: '🦇', en: 'Bat', bn: 'বাদুড়' },
    { char: '🐺', en: 'Wolf', bn: 'নেকড়ে' },
    { char: '🐴', en: 'Horse', bn: 'ঘোড়া' },
    { char: '🦄', en: 'Unicorn', bn: 'ইউনিকর্ন' },
    { char: '🐝', en: 'Bee', bn: 'মৌমাছি' },
    { char: '🐛', en: 'Caterpillar', bn: 'শুঁয়োপোকা' },
    { char: '🦋', en: 'Butterfly', bn: 'প্রজাপতি' },
    { char: '🐌', en: 'Snail', bn: 'শামুক' },
    { char: '🐞', en: 'Ladybug', bn: 'লেডিবাগ' },
    { char: '🐢', en: 'Turtle', bn: 'কচ্ছপ' },
    { char: '🐍', en: 'Snake', bn: 'সাপ' },
    { char: '🦎', en: 'Lizard', bn: 'টিকটিকি' },
    { char: '🦖', en: 'Dinosaur', bn: 'ডাইনোসর' },
    { char: '🐉', en: 'Dragon', bn: 'ড্রাগন' },
    { char: '🐳', en: 'Whale', bn: 'তিমি' },
    { char: '🐬', en: 'Dolphin', bn: 'ডলফিন' },
    { char: '🐟', en: 'Fish', bn: 'মাছ' },
    { char: '🐠', en: 'Tropical Fish', bn: 'রঙিন মাছ' },
    { char: '🦈', en: 'Shark', bn: 'হাঙর' },
    { char: '🐙', en: 'Octopus', bn: 'অক্টোপাস' },
    { char: '🦀', en: 'Crab', bn: 'কাঁকড়া' },
    { char: '🐘', en: 'Elephant', bn: 'হাতি' },
    { char: '🦏', en: 'Rhino', bn: 'গন্ডার' },
    { char: '🦛', en: 'Hippo', bn: 'জলহস্তী' },
    { char: '🐫', en: 'Camel', bn: 'উট' },
    { char: '🦒', en: 'Giraffe', bn: 'জিরাফ' },
    { char: '🦘', en: 'Kangaroo', bn: 'ক্যাঙ্গারু' },
    { char: '🦓', en: 'Zebra', bn: 'জেব্রা' },
    { char: '🦍', en: 'Gorilla', bn: 'গরিলা' },
    { char: '🦌', en: 'Deer', bn: 'হরিণ' },
    { char: '🐑', en: 'Sheep', bn: 'ভেড়া' },
    { char: '🐐', en: 'Goat', bn: 'ছাগল' },
    { char: '🦙', en: 'Llama', bn: 'লামা' },
    { char: '🦥', en: 'Sloth', bn: 'স্লথ' },
    { char: '🦦', en: 'Otter', bn: 'ভোঁদড়' },
    { char: '🦩', en: 'Flamingo', bn: 'ফ্লেমিঙ্গো' },
    { char: '🦚', en: 'Peacock', bn: 'ময়ূর' },
    { char: '🦜', en: 'Parrot', bn: 'টিয়া' },
    { char: '🦢', en: 'Swan', bn: 'রাজহাঁস' },
    { char: '🐓', en: 'Rooster', bn: 'মোরগ' },
    { char: '🦔', en: 'Hedgehog', bn: 'শজারু' }
  ];

  // Bright, cheerful general emojis — faces, food, toys, nature.
  var EMOJIS = [
    { char: '⭐', en: 'Star', bn: 'তারা' },
    { char: '🌟', en: 'Sparkle Star', bn: 'ঝলমলে তারা' },
    { char: '✨', en: 'Sparkles', bn: 'ঝিকিমিকি' },
    { char: '❤️', en: 'Heart', bn: 'ভালোবাসা' },
    { char: '🧡', en: 'Orange Heart', bn: 'কমলা হৃদয়' },
    { char: '💛', en: 'Yellow Heart', bn: 'হলুদ হৃদয়' },
    { char: '💚', en: 'Green Heart', bn: 'সবুজ হৃদয়' },
    { char: '💙', en: 'Blue Heart', bn: 'নীল হৃদয়' },
    { char: '💜', en: 'Purple Heart', bn: 'বেগুনি হৃদয়' },
    { char: '🌈', en: 'Rainbow', bn: 'রংধনু' },
    { char: '☀️', en: 'Sun', bn: 'সূর্য' },
    { char: '🌙', en: 'Moon', bn: 'চাঁদ' },
    { char: '☁️', en: 'Cloud', bn: 'মেঘ' },
    { char: '⚡', en: 'Lightning', bn: 'বিদ্যুৎ' },
    { char: '🔥', en: 'Fire', bn: 'আগুন' },
    { char: '❄️', en: 'Snowflake', bn: 'তুষার' },
    { char: '🌸', en: 'Flower', bn: 'ফুল' },
    { char: '🌻', en: 'Sunflower', bn: 'সূর্যমুখী' },
    { char: '🌷', en: 'Tulip', bn: 'টিউলিপ' },
    { char: '🍀', en: 'Clover', bn: 'ক্লোভার' },
    { char: '🎈', en: 'Balloon', bn: 'বেলুন' },
    { char: '🎉', en: 'Party', bn: 'উৎসব' },
    { char: '🎊', en: 'Confetti', bn: 'কনফেটি' },
    { char: '🎀', en: 'Bow', bn: 'ফিতা' },
    { char: '🎁', en: 'Present', bn: 'উপহার' },
    { char: '⚽', en: 'Ball', bn: 'বল' },
    { char: '🏀', en: 'Basketball', bn: 'বাস্কেটবল' },
    { char: '🎨', en: 'Paint', bn: 'রং' },
    { char: '🚗', en: 'Car', bn: 'গাড়ি' },
    { char: '🚕', en: 'Taxi', bn: 'ট্যাক্সি' },
    { char: '🚒', en: 'Fire Truck', bn: 'দমকল' },
    { char: '🚜', en: 'Tractor', bn: 'ট্রাক্টর' },
    { char: '✈️', en: 'Airplane', bn: 'বিমান' },
    { char: '🚀', en: 'Rocket', bn: 'রকেট' },
    { char: '🚂', en: 'Train', bn: 'ট্রেন' },
    { char: '⛵', en: 'Boat', bn: 'নৌকা' },
    { char: '🚲', en: 'Bicycle', bn: 'সাইকেল' },
    { char: '🍎', en: 'Apple', bn: 'আপেল' },
    { char: '🍌', en: 'Banana', bn: 'কলা' },
    { char: '🍓', en: 'Strawberry', bn: 'স্ট্রবেরি' },
    { char: '🍇', en: 'Grapes', bn: 'আঙুর' },
    { char: '🍉', en: 'Watermelon', bn: 'তরমুজ' },
    { char: '🍊', en: 'Orange', bn: 'কমলা' },
    { char: '🍒', en: 'Cherry', bn: 'চেরি' },
    { char: '🍦', en: 'Ice Cream', bn: 'আইসক্রিম' },
    { char: '🍩', en: 'Donut', bn: 'ডোনাট' },
    { char: '🍪', en: 'Cookie', bn: 'কুকি' },
    { char: '🎂', en: 'Cake', bn: 'কেক' },
    { char: '🍕', en: 'Pizza', bn: 'পিজা' },
    { char: '🍭', en: 'Lollipop', bn: 'ললিপপ' },
    { char: '🍬', en: 'Candy', bn: 'ক্যান্ডি' },
    { char: '😀', en: 'Happy Face', bn: 'হাসিমুখ' },
    { char: '😄', en: 'Big Smile', bn: 'বড় হাসি' },
    { char: '😁', en: 'Grin', bn: 'খুশি হাসি' },
    { char: '🥰', en: 'Love Face', bn: 'আদুরে মুখ' },
    { char: '😍', en: 'Hearts Eyes', bn: 'হৃদয় চোখ' },
    { char: '🤩', en: 'Star Eyes', bn: 'তারা চোখ' },
    { char: '😎', en: 'Cool Face', bn: 'দারুণ মুখ' },
    { char: '🤗', en: 'Hug', bn: 'আলিঙ্গন' },
    { char: '😋', en: 'Yummy', bn: 'মজাদার' },
    { char: '🥳', en: 'Party Face', bn: 'খুশি মুখ' },
    { char: '👋', en: 'Wave', bn: 'টাটা' },
    { char: '👍', en: 'Thumbs Up', bn: 'শাবাশ' },
    { char: '👏', en: 'Clap', bn: 'হাততালি' },
    { char: '🙌', en: 'Hooray', bn: 'হুররে' }
  ];

  global.GAME_DATA = {
    animals: ANIMALS,
    emojis: EMOJIS
  };
})(window);
