/*
 * data.js — Curated content for the Baby Keyboard Game.
 *
 * Two pools of items. Each item is { char, name } where:
 *   - char : the emoji glyph shown on screen (also upgraded to a crisp SVG by Twemoji)
 *   - name : a toddler-friendly word spoken aloud via the Web Speech API
 *
 * Exposed on the global object so plain <script> tags (no bundler / no modules)
 * keep working when opened directly from disk or served by GitHub Pages.
 */
(function (global) {
  'use strict';

  // Friendly, recognisable animals for a two-year-old.
  var ANIMALS = [
    { char: '🐶', name: 'Dog' },
    { char: '🐱', name: 'Cat' },
    { char: '🐭', name: 'Mouse' },
    { char: '🐹', name: 'Hamster' },
    { char: '🐰', name: 'Bunny' },
    { char: '🦊', name: 'Fox' },
    { char: '🐻', name: 'Bear' },
    { char: '🐼', name: 'Panda' },
    { char: '🐨', name: 'Koala' },
    { char: '🐯', name: 'Tiger' },
    { char: '🦁', name: 'Lion' },
    { char: '🐮', name: 'Cow' },
    { char: '🐷', name: 'Pig' },
    { char: '🐸', name: 'Frog' },
    { char: '🐵', name: 'Monkey' },
    { char: '🐔', name: 'Chicken' },
    { char: '🐧', name: 'Penguin' },
    { char: '🐦', name: 'Bird' },
    { char: '🐤', name: 'Baby Chick' },
    { char: '🦆', name: 'Duck' },
    { char: '🦉', name: 'Owl' },
    { char: '🦇', name: 'Bat' },
    { char: '🐺', name: 'Wolf' },
    { char: '🐴', name: 'Horse' },
    { char: '🦄', name: 'Unicorn' },
    { char: '🐝', name: 'Bee' },
    { char: '🐛', name: 'Caterpillar' },
    { char: '🦋', name: 'Butterfly' },
    { char: '🐌', name: 'Snail' },
    { char: '🐞', name: 'Ladybug' },
    { char: '🐢', name: 'Turtle' },
    { char: '🐍', name: 'Snake' },
    { char: '🦎', name: 'Lizard' },
    { char: '🦖', name: 'Dinosaur' },
    { char: '🐉', name: 'Dragon' },
    { char: '🐳', name: 'Whale' },
    { char: '🐬', name: 'Dolphin' },
    { char: '🐟', name: 'Fish' },
    { char: '🐠', name: 'Tropical Fish' },
    { char: '🦈', name: 'Shark' },
    { char: '🐙', name: 'Octopus' },
    { char: '🦀', name: 'Crab' },
    { char: '🐘', name: 'Elephant' },
    { char: '🦏', name: 'Rhino' },
    { char: '🦛', name: 'Hippo' },
    { char: '🐫', name: 'Camel' },
    { char: '🦒', name: 'Giraffe' },
    { char: '🦘', name: 'Kangaroo' },
    { char: '🦓', name: 'Zebra' },
    { char: '🦍', name: 'Gorilla' },
    { char: '🦌', name: 'Deer' },
    { char: '🐑', name: 'Sheep' },
    { char: '🐐', name: 'Goat' },
    { char: '🦙', name: 'Llama' },
    { char: '🦥', name: 'Sloth' },
    { char: '🦦', name: 'Otter' },
    { char: '🦩', name: 'Flamingo' },
    { char: '🦚', name: 'Peacock' },
    { char: '🦜', name: 'Parrot' },
    { char: '🦢', name: 'Swan' },
    { char: '🐓', name: 'Rooster' },
    { char: '🦔', name: 'Hedgehog' }
  ];

  // Bright, cheerful general emojis — faces, food, toys, nature.
  var EMOJIS = [
    { char: '⭐', name: 'Star' },
    { char: '🌟', name: 'Sparkle Star' },
    { char: '✨', name: 'Sparkles' },
    { char: '❤️', name: 'Heart' },
    { char: '🧡', name: 'Orange Heart' },
    { char: '💛', name: 'Yellow Heart' },
    { char: '💚', name: 'Green Heart' },
    { char: '💙', name: 'Blue Heart' },
    { char: '💜', name: 'Purple Heart' },
    { char: '🌈', name: 'Rainbow' },
    { char: '☀️', name: 'Sun' },
    { char: '🌙', name: 'Moon' },
    { char: '☁️', name: 'Cloud' },
    { char: '⚡', name: 'Lightning' },
    { char: '🔥', name: 'Fire' },
    { char: '❄️', name: 'Snowflake' },
    { char: '🌸', name: 'Flower' },
    { char: '🌻', name: 'Sunflower' },
    { char: '🌷', name: 'Tulip' },
    { char: '🍀', name: 'Clover' },
    { char: '🎈', name: 'Balloon' },
    { char: '🎉', name: 'Party' },
    { char: '🎊', name: 'Confetti' },
    { char: '🎀', name: 'Bow' },
    { char: '🎁', name: 'Present' },
    { char: '⚽', name: 'Ball' },
    { char: '🏀', name: 'Basketball' },
    { char: '🎨', name: 'Paint' },
    { char: '🚗', name: 'Car' },
    { char: '🚕', name: 'Taxi' },
    { char: '🚒', name: 'Fire Truck' },
    { char: '🚜', name: 'Tractor' },
    { char: '✈️', name: 'Airplane' },
    { char: '🚀', name: 'Rocket' },
    { char: '🚂', name: 'Train' },
    { char: '⛵', name: 'Boat' },
    { char: '🚲', name: 'Bicycle' },
    { char: '🍎', name: 'Apple' },
    { char: '🍌', name: 'Banana' },
    { char: '🍓', name: 'Strawberry' },
    { char: '🍇', name: 'Grapes' },
    { char: '🍉', name: 'Watermelon' },
    { char: '🍊', name: 'Orange' },
    { char: '🍒', name: 'Cherry' },
    { char: '🍦', name: 'Ice Cream' },
    { char: '🍩', name: 'Donut' },
    { char: '🍪', name: 'Cookie' },
    { char: '🎂', name: 'Cake' },
    { char: '🍕', name: 'Pizza' },
    { char: '🍭', name: 'Lollipop' },
    { char: '🍬', name: 'Candy' },
    { char: '😀', name: 'Happy Face' },
    { char: '😄', name: 'Big Smile' },
    { char: '😁', name: 'Grin' },
    { char: '🥰', name: 'Love Face' },
    { char: '😍', name: 'Hearts Eyes' },
    { char: '🤩', name: 'Star Eyes' },
    { char: '😎', name: 'Cool Face' },
    { char: '🤗', name: 'Hug' },
    { char: '😋', name: 'Yummy' },
    { char: '🥳', name: 'Party Face' },
    { char: '👋', name: 'Wave' },
    { char: '👍', name: 'Thumbs Up' },
    { char: '👏', name: 'Clap' },
    { char: '🙌', name: 'Hooray' }
  ];

  global.GAME_DATA = {
    animals: ANIMALS,
    emojis: EMOJIS
  };
})(window);
